import type { CefrLevelId } from '@langue-buster/shared';

import type { GrammaticalGender, ItemType, PartOfSpeech } from './index.js';

export type Phase11TopicDefinition = Readonly<{
  id: string;
  slug: string;
  title: string;
  description: string;
  cefrLevels: readonly CefrLevelId[];
}>;

export type Phase11LessonDefinition = Readonly<{
  id: string;
  slug: string;
  title: string;
  description: string;
  cefrLevel: CefrLevelId;
  topicIds: readonly string[];
}>;

export type Phase11SourceEntry = Readonly<{
  levelId: CefrLevelId;
  topicId: string;
  lessonId: string;
  slug: string;
  lemma: string;
  surfaceForm: string;
  translationRu: string;
  partOfSpeech: PartOfSpeech;
  itemType: ItemType;
  article?: string;
  gender?: GrammaticalGender;
  exampleFr?: string;
  exampleRu?: string;
}>;

function noun(
  levelId: CefrLevelId,
  topicId: string,
  lessonId: string,
  slug: string,
  lemma: string,
  translationRu: string,
  article: string,
  gender: GrammaticalGender,
): Phase11SourceEntry {
  return {
    levelId,
    topicId,
    lessonId,
    slug,
    lemma,
    surfaceForm: lemma,
    translationRu,
    partOfSpeech: 'noun',
    itemType: 'word',
    article,
    gender,
  };
}

function verb(
  levelId: CefrLevelId,
  topicId: string,
  lessonId: string,
  slug: string,
  lemma: string,
  translationRu: string,
  exampleFr: string,
  exampleRu: string,
): Phase11SourceEntry {
  return {
    levelId,
    topicId,
    lessonId,
    slug,
    lemma,
    surfaceForm: lemma,
    translationRu,
    partOfSpeech: 'verb',
    itemType: 'word',
    exampleFr,
    exampleRu,
  };
}

function adjective(
  levelId: CefrLevelId,
  topicId: string,
  lessonId: string,
  slug: string,
  lemma: string,
  translationRu: string,
): Phase11SourceEntry {
  return {
    levelId,
    topicId,
    lessonId,
    slug,
    lemma,
    surfaceForm: lemma,
    translationRu,
    partOfSpeech: 'adjective',
    itemType: 'word',
  };
}

function determiner(
  levelId: CefrLevelId,
  topicId: string,
  lessonId: string,
  slug: string,
  lemma: string,
  translationRu: string,
): Phase11SourceEntry {
  return {
    levelId,
    topicId,
    lessonId,
    slug,
    lemma,
    surfaceForm: lemma,
    translationRu,
    partOfSpeech: 'determiner',
    itemType: 'word',
  };
}

function phrase(
  levelId: CefrLevelId,
  topicId: string,
  lessonId: string,
  slug: string,
  surfaceForm: string,
  translationRu: string,
  exampleFr?: string,
  exampleRu?: string,
): Phase11SourceEntry {
  return {
    levelId,
    topicId,
    lessonId,
    slug,
    lemma: surfaceForm,
    surfaceForm,
    translationRu,
    partOfSpeech: 'expression',
    itemType: 'phrase',
    exampleFr,
    exampleRu,
  };
}

export const phase11TopicDefinitions: readonly Phase11TopicDefinition[] = [
  {
    id: 'topic.greetings',
    slug: 'greetings',
    title: 'Приветствия и вежливость',
    description: 'Базовые приветствия, ответы и вежливые формулы для старта общения.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.family',
    slug: 'family',
    title: 'Семья и отношения',
    description: 'Слова про семью, родственников и близкое окружение.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.food',
    slug: 'food',
    title: 'Еда и напитки',
    description: 'Базовая еда, напитки и приёмы пищи для A1/A2.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.colors-adjectives',
    slug: 'colors-adjectives',
    title: 'Цвета и простые признаки',
    description: 'Цвета и повседневные описательные прилагательные.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.numbers-time',
    slug: 'numbers-time',
    title: 'Числа и время',
    description: 'Числительные и базовые слова о времени.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.everyday-objects-home',
    slug: 'everyday-objects-home',
    title: 'Предметы и дом',
    description: 'Предметы повседневного быта и домашнего пространства.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.daily-routine',
    slug: 'daily-routine',
    title: 'Ежедневные действия',
    description: 'Глаголы и выражения про ежедневную рутину.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.school-work-basics',
    slug: 'school-work-basics',
    title: 'Учёба и работа',
    description: 'Базовые слова про школу, документы и рабочие реалии.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.transport-travel',
    slug: 'transport-travel',
    title: 'Транспорт и поездки',
    description: 'Транспорт, поездки и базовая дорожная лексика.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.shopping',
    slug: 'shopping',
    title: 'Покупки',
    description: 'Слова про магазин, оплату, выбор и покупки.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.body-health-basics',
    slug: 'body-health-basics',
    title: 'Тело и здоровье',
    description: 'Базовые части тела и простая лексика о самочувствии.',
    cefrLevels: ['A1', 'A2'],
  },
  {
    id: 'topic.common-verbs',
    slug: 'common-verbs',
    title: 'Частые глаголы',
    description: 'Наиболее частотные французские глаголы для запуска речи.',
    cefrLevels: ['A1', 'A2'],
  },
] as const;

export const phase11LessonDefinitions: readonly Phase11LessonDefinition[] = [
  {
    id: 'lesson.a1.greetings-family',
    slug: 'a1-greetings-family',
    title: 'A1: приветствия и семья',
    description: 'Первые устойчивые фразы и базовые семейные слова.',
    cefrLevel: 'A1',
    topicIds: ['topic.greetings', 'topic.family'],
  },
  {
    id: 'lesson.a1.food-shopping',
    slug: 'a1-food-shopping',
    title: 'A1: еда и покупки',
    description: 'Простая лексика про магазин, деньги и базовые продукты.',
    cefrLevel: 'A1',
    topicIds: ['topic.food', 'topic.shopping'],
  },
  {
    id: 'lesson.a1.colors-adjectives',
    slug: 'a1-colors-adjectives',
    title: 'A1: цвета и признаки',
    description: 'Простые цвета и базовые прилагательные для описания.',
    cefrLevel: 'A1',
    topicIds: ['topic.colors-adjectives'],
  },
  {
    id: 'lesson.a1.numbers-time',
    slug: 'a1-numbers-time',
    title: 'A1: числа и время',
    description: 'Счёт до десяти и базовые временные слова.',
    cefrLevel: 'A1',
    topicIds: ['topic.numbers-time'],
  },
  {
    id: 'lesson.a1.objects-home',
    slug: 'a1-objects-home',
    title: 'A1: предметы и дом',
    description: 'Предметы вокруг нас и базовая домашняя лексика.',
    cefrLevel: 'A1',
    topicIds: ['topic.everyday-objects-home'],
  },
  {
    id: 'lesson.a1.daily-routine',
    slug: 'a1-daily-routine',
    title: 'A1: ежедневные действия',
    description: 'Глаголы про распорядок дня и повседневные действия.',
    cefrLevel: 'A1',
    topicIds: ['topic.daily-routine'],
  },
  {
    id: 'lesson.a1.school-work',
    slug: 'a1-school-work',
    title: 'A1: учёба и работа',
    description: 'Слова про школу, задания и базовую учебную среду.',
    cefrLevel: 'A1',
    topicIds: ['topic.school-work-basics'],
  },
  {
    id: 'lesson.a1.transport-travel',
    slug: 'a1-transport-travel',
    title: 'A1: транспорт и поездки',
    description: 'Базовые слова про транспорт и перемещение.',
    cefrLevel: 'A1',
    topicIds: ['topic.transport-travel'],
  },
  {
    id: 'lesson.a1.shopping-body',
    slug: 'a1-shopping-body',
    title: 'A1: покупки и самочувствие',
    description: 'Практичные слова для магазина и простого описания тела.',
    cefrLevel: 'A1',
    topicIds: ['topic.shopping', 'topic.body-health-basics'],
  },
  {
    id: 'lesson.a1.common-verbs',
    slug: 'a1-common-verbs',
    title: 'A1: самые частые глаголы',
    description: 'Ключевые французские глаголы для первых фраз.',
    cefrLevel: 'A1',
    topicIds: ['topic.common-verbs'],
  },
  {
    id: 'lesson.a2.greetings-family',
    slug: 'a2-greetings-family',
    title: 'A2: общение и окружение',
    description: 'Более развернутые формулы общения и родственные связи.',
    cefrLevel: 'A2',
    topicIds: ['topic.greetings', 'topic.family'],
  },
  {
    id: 'lesson.a2.food-shopping',
    slug: 'a2-food-shopping',
    title: 'A2: еда, заказ и выбор',
    description: 'Приёмы пищи, заказ и слова про выбор в магазине.',
    cefrLevel: 'A2',
    topicIds: ['topic.food', 'topic.shopping'],
  },
  {
    id: 'lesson.a2.colors-adjectives',
    slug: 'a2-colors-adjectives',
    title: 'A2: описание предметов и людей',
    description: 'Больше качественных признаков и описательной лексики.',
    cefrLevel: 'A2',
    topicIds: ['topic.colors-adjectives'],
  },
  {
    id: 'lesson.a2.numbers-time',
    slug: 'a2-numbers-time',
    title: 'A2: время и планирование',
    description: 'Расширенная временная лексика и числа после десяти.',
    cefrLevel: 'A2',
    topicIds: ['topic.numbers-time'],
  },
  {
    id: 'lesson.a2.objects-home',
    slug: 'a2-objects-home',
    title: 'A2: дом и повседневный интерьер',
    description: 'Комнаты, мебель и детали домашнего пространства.',
    cefrLevel: 'A2',
    topicIds: ['topic.everyday-objects-home'],
  },
  {
    id: 'lesson.a2.daily-routine',
    slug: 'a2-daily-routine',
    title: 'A2: планы и рутина',
    description: 'Расширенные глаголы про повседневные действия и планы.',
    cefrLevel: 'A2',
    topicIds: ['topic.daily-routine'],
  },
  {
    id: 'lesson.a2.school-work',
    slug: 'a2-school-work',
    title: 'A2: документы и работа',
    description: 'Базовая рабочая и учебная административная лексика.',
    cefrLevel: 'A2',
    topicIds: ['topic.school-work-basics'],
  },
  {
    id: 'lesson.a2.transport-travel',
    slug: 'a2-transport-travel',
    title: 'A2: дорога и путешествие',
    description: 'Пограничные дорожные и гостиничные слова для A2.',
    cefrLevel: 'A2',
    topicIds: ['topic.transport-travel'],
  },
  {
    id: 'lesson.a2.body-health',
    slug: 'a2-body-health',
    title: 'A2: здоровье и самочувствие',
    description: 'Более точные слова про тело, лекарства и симптомы.',
    cefrLevel: 'A2',
    topicIds: ['topic.body-health-basics'],
  },
  {
    id: 'lesson.a2.common-verbs',
    slug: 'a2-common-verbs',
    title: 'A2: глаголы для расширения речи',
    description: 'Частые глаголы A2 для повседневных действий и решений.',
    cefrLevel: 'A2',
    topicIds: ['topic.common-verbs'],
  },
] as const;

export const phase11A1SourceList: readonly Phase11SourceEntry[] = [
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'bonjour', 'bonjour', 'здравствуйте', 'Bonjour, Madame.', 'Здравствуйте, мадам.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'salut', 'salut', 'привет', 'Salut, Paul.', 'Привет, Поль.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'bonsoir', 'bonsoir', 'добрый вечер', 'Bonsoir, Claire.', 'Добрый вечер, Клер.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'au-revoir', 'au revoir', 'до свидания', 'Au revoir, à demain.', 'До свидания, до завтра.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'a-bientot', 'à bientôt', 'до скорого', 'À bientôt, Marie.', 'До скорого, Мари.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'merci', 'merci', 'спасибо', 'Merci pour le café.', 'Спасибо за кофе.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'merci-beaucoup', 'merci beaucoup', 'большое спасибо', 'Merci beaucoup, Anna.', 'Большое спасибо, Анна.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 's-il-vous-plait', "s'il vous plaît", 'пожалуйста', "Un thé, s'il vous plaît.", 'Чай, пожалуйста.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'de-rien', 'de rien', 'не за что', 'De rien, avec plaisir.', 'Не за что, с удовольствием.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'pardon', 'pardon', 'извините', 'Pardon, madame.', 'Извините, мадам.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'excuse-moi', 'excuse-moi', 'извини меня', 'Excuse-moi, Pierre.', 'Извини меня, Пьер.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'oui', 'oui', 'да', 'Oui, bien sûr.', 'Да, конечно.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'non', 'non', 'нет', 'Non, merci.', 'Нет, спасибо.'),
  phrase('A1', 'topic.greetings', 'lesson.a1.greetings-family', 'd-accord', "d'accord", 'хорошо', "D'accord, j'arrive.", 'Хорошо, я иду.'),

  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'famille', 'famille', 'семья', 'la', 'feminine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'mere', 'mère', 'мать', 'la', 'feminine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'pere', 'père', 'отец', 'le', 'masculine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'frere', 'frère', 'брат', 'le', 'masculine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'soeur', 'sœur', 'сестра', 'la', 'feminine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'grand-mere', 'grand-mère', 'бабушка', 'la', 'feminine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'grand-pere', 'grand-père', 'дедушка', 'le', 'masculine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'fils', 'fils', 'сын', 'le', 'masculine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'fille', 'fille', 'дочь', 'la', 'feminine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'mari', 'mari', 'муж', 'le', 'masculine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'femme', 'femme', 'жена', 'la', 'feminine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'enfant', 'enfant', 'ребёнок', "l'", 'masculine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'bebe', 'bébé', 'малыш', 'le', 'masculine'),
  noun('A1', 'topic.family', 'lesson.a1.greetings-family', 'cousin', 'cousin', 'двоюродный брат', 'le', 'masculine'),

  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'pain', 'pain', 'хлеб', 'le', 'masculine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'eau', 'eau', 'вода', "l'", 'feminine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'lait', 'lait', 'молоко', 'le', 'masculine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'cafe', 'café', 'кофе', 'le', 'masculine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'the', 'thé', 'чай', 'le', 'masculine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'pomme', 'pomme', 'яблоко', 'la', 'feminine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'banane', 'banane', 'банан', 'la', 'feminine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'orange', 'orange', 'апельсин', "l'", 'feminine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'fromage', 'fromage', 'сыр', 'le', 'masculine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'soupe', 'soupe', 'суп', 'la', 'feminine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'salade', 'salade', 'салат', 'la', 'feminine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'viande', 'viande', 'мясо', 'la', 'feminine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'poisson', 'poisson', 'рыба', 'le', 'masculine'),
  noun('A1', 'topic.food', 'lesson.a1.food-shopping', 'riz', 'riz', 'рис', 'le', 'masculine'),

  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'rouge', 'rouge', 'красный'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'bleu', 'bleu', 'синий'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'vert', 'vert', 'зелёный'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'jaune', 'jaune', 'жёлтый'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'noir', 'noir', 'чёрный'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'blanc', 'blanc', 'белый'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'gris', 'gris', 'серый'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'grand', 'grand', 'большой'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'petit', 'petit', 'маленький'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'bon', 'bon', 'хороший'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'mauvais', 'mauvais', 'плохой'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'chaud', 'chaud', 'тёплый'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'froid', 'froid', 'холодный'),
  adjective('A1', 'topic.colors-adjectives', 'lesson.a1.colors-adjectives', 'joli', 'joli', 'красивый'),

  determiner('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'un', 'un', 'один'),
  determiner('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'deux', 'deux', 'два'),
  determiner('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'trois', 'trois', 'три'),
  determiner('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'quatre', 'quatre', 'четыре'),
  determiner('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'cinq', 'cinq', 'пять'),
  determiner('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'six', 'six', 'шесть'),
  determiner('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'sept', 'sept', 'семь'),
  determiner('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'huit', 'huit', 'восемь'),
  determiner('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'neuf', 'neuf', 'девять'),
  determiner('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'dix', 'dix', 'десять'),
  noun('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'heure', 'heure', 'час', "l'", 'feminine'),
  noun('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'matin', 'matin', 'утро', 'le', 'masculine'),
  noun('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'soir', 'soir', 'вечер', 'le', 'masculine'),
  noun('A1', 'topic.numbers-time', 'lesson.a1.numbers-time', 'jour', 'jour', 'день', 'le', 'masculine'),

  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'table', 'table', 'стол', 'la', 'feminine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'chaise', 'chaise', 'стул', 'la', 'feminine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'porte', 'porte', 'дверь', 'la', 'feminine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'fenetre', 'fenêtre', 'окно', 'la', 'feminine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'lit', 'lit', 'кровать', 'le', 'masculine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'lampe', 'lampe', 'лампа', 'la', 'feminine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'cle', 'clé', 'ключ', 'la', 'feminine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'sac', 'sac', 'сумка', 'le', 'masculine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'livre', 'livre', 'книга', 'le', 'masculine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'stylo', 'stylo', 'ручка', 'le', 'masculine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'telephone', 'téléphone', 'телефон', 'le', 'masculine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'tasse', 'tasse', 'чашка', 'la', 'feminine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'assiette', 'assiette', 'тарелка', "l'", 'feminine'),
  noun('A1', 'topic.everyday-objects-home', 'lesson.a1.objects-home', 'ordinateur', 'ordinateur', 'компьютер', "l'", 'masculine'),

  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'se-lever', 'se lever', 'вставать', 'Je me lève tôt.', 'Я встаю рано.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'se-laver', 'se laver', 'мыться', 'Je me lave vite.', 'Я быстро моюсь.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 's-habiller', "s'habiller", 'одеваться', "Je m'habille maintenant.", 'Я сейчас одеваюсь.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'manger', 'manger', 'есть', 'Je mange ici.', 'Я ем здесь.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'boire', 'boire', 'пить', "Je bois de l'eau.", 'Я пью воду.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'travailler', 'travailler', 'работать', "Je travaille aujourd'hui.", 'Я работаю сегодня.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'etudier', 'étudier', 'учиться', "J'étudie le français.", 'Я учу французский.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'dormir', 'dormir', 'спать', 'Je dors bien.', 'Я сплю хорошо.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'marcher', 'marcher', 'идти пешком', 'Je marche au parc.', 'Я иду пешком в парк.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'rentrer', 'rentrer', 'возвращаться домой', 'Je rentre à la maison.', 'Я возвращаюсь домой.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'commencer', 'commencer', 'начинать', 'Je commence maintenant.', 'Я начинаю сейчас.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'finir', 'finir', 'заканчивать', 'Je finis à six heures.', 'Я заканчиваю в шесть часов.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'ecouter', 'écouter', 'слушать', "J'écoute la radio.", 'Я слушаю радио.'),
  verb('A1', 'topic.daily-routine', 'lesson.a1.daily-routine', 'regarder', 'regarder', 'смотреть', 'Je regarde la rue.', 'Я смотрю на улицу.'),

  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'ecole', 'école', 'школа', "l'", 'feminine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'classe', 'classe', 'класс', 'la', 'feminine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'professeur', 'professeur', 'учитель', 'le', 'masculine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'tableau', 'tableau', 'доска', 'le', 'masculine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'exercice', 'exercice', 'упражнение', "l'", 'masculine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'question', 'question', 'вопрос', 'la', 'feminine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'reponse', 'réponse', 'ответ', 'la', 'feminine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'bureau', 'bureau', 'письменный стол', 'le', 'masculine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'cahier', 'cahier', 'тетрадь', 'le', 'masculine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'papier', 'papier', 'бумага', 'le', 'masculine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'travail', 'travail', 'работа', 'le', 'masculine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'pause', 'pause', 'перерыв', 'la', 'feminine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'examen', 'examen', 'экзамен', "l'", 'masculine'),
  noun('A1', 'topic.school-work-basics', 'lesson.a1.school-work', 'mot', 'mot', 'слово', 'le', 'masculine'),

  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'voiture', 'voiture', 'машина', 'la', 'feminine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'bus', 'bus', 'автобус', 'le', 'masculine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'train', 'train', 'поезд', 'le', 'masculine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'metro', 'métro', 'метро', 'le', 'masculine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'velo', 'vélo', 'велосипед', 'le', 'masculine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'gare', 'gare', 'вокзал', 'la', 'feminine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'billet', 'billet', 'билет', 'le', 'masculine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'route', 'route', 'дорога', 'la', 'feminine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'rue', 'rue', 'улица', 'la', 'feminine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'station', 'station', 'станция', 'la', 'feminine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'taxi', 'taxi', 'такси', 'le', 'masculine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'avion', 'avion', 'самолёт', "l'", 'masculine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'bateau', 'bateau', 'лодка', 'le', 'masculine'),
  noun('A1', 'topic.transport-travel', 'lesson.a1.transport-travel', 'carte', 'carte', 'карта', 'la', 'feminine'),

  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'magasin', 'magasin', 'магазин', 'le', 'masculine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'marche', 'marché', 'рынок', 'le', 'masculine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'prix', 'prix', 'цена', 'le', 'masculine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'argent', 'argent', 'деньги', "l'", 'masculine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'euro', 'euro', 'евро', "l'", 'masculine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'caisse', 'caisse', 'касса', 'la', 'feminine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'vendeur', 'vendeur', 'продавец', 'le', 'masculine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'vendeuse', 'vendeuse', 'продавщица', 'la', 'feminine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'achat', 'achat', 'покупка', "l'", 'masculine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'taille', 'taille', 'размер', 'la', 'feminine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'client', 'client', 'клиент', 'le', 'masculine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'cliente', 'cliente', 'клиентка', 'la', 'feminine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'monnaie', 'monnaie', 'мелочь', 'la', 'feminine'),
  noun('A1', 'topic.shopping', 'lesson.a1.shopping-body', 'recu', 'reçu', 'чек', 'le', 'masculine'),

  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'tete', 'tête', 'голова', 'la', 'feminine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'main', 'main', 'рука', 'la', 'feminine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'bras', 'bras', 'рука до кисти', 'le', 'masculine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'jambe', 'jambe', 'нога', 'la', 'feminine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'pied', 'pied', 'ступня', 'le', 'masculine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'dos', 'dos', 'спина', 'le', 'masculine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'ventre', 'ventre', 'живот', 'le', 'masculine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'corps', 'corps', 'тело', 'le', 'masculine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'medecin', 'médecin', 'врач', 'le', 'masculine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'hopital', 'hôpital', 'больница', "l'", 'masculine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'sante', 'santé', 'здоровье', 'la', 'feminine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'fievre', 'fièvre', 'температура', 'la', 'feminine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'douleur', 'douleur', 'боль', 'la', 'feminine'),
  noun('A1', 'topic.body-health-basics', 'lesson.a1.shopping-body', 'bouche', 'bouche', 'рот', 'la', 'feminine'),

  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'etre', 'être', 'быть', 'Je suis ici.', 'Я здесь.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'avoir', 'avoir', 'иметь', "J'ai un sac.", 'У меня есть сумка.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'aller', 'aller', 'идти', "Je vais à l'école.", 'Я иду в школу.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'venir', 'venir', 'приходить', 'Je viens demain.', 'Я приду завтра.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'faire', 'faire', 'делать', 'Je fais un exercice.', 'Я делаю упражнение.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'parler', 'parler', 'говорить', 'Je parle français.', 'Я говорю по-французски.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'aimer', 'aimer', 'любить', "J'aime la musique.", 'Я люблю музыку.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'trouver', 'trouver', 'находить', 'Je trouve la clé.', 'Я нахожу ключ.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'donner', 'donner', 'давать', 'Je donne le livre.', 'Я даю книгу.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'prendre', 'prendre', 'брать', 'Je prends le bus.', 'Я сажусь на автобус.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'ouvrir', 'ouvrir', 'открывать', "J'ouvre la porte.", 'Я открываю дверь.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'fermer', 'fermer', 'закрывать', 'Je ferme la fenêtre.', 'Я закрываю окно.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'attendre', 'attendre', 'ждать', "J'attends le train.", 'Я жду поезд.'),
  verb('A1', 'topic.common-verbs', 'lesson.a1.common-verbs', 'porter', 'porter', 'носить', 'Je porte un sac.', 'Я ношу сумку.'),
] as const;

export const phase11A2SourceList: readonly Phase11SourceEntry[] = [
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'comment-ca-va', 'comment ça va ?', 'как дела?', 'Comment ça va ?', 'Как дела?'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'ca-va-bien', 'ça va bien', 'всё хорошо', 'Ça va bien, merci.', 'Всё хорошо, спасибо.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'ca-va-mal', 'ça va mal', 'всё плохо', 'Ça va mal aujourd’hui.', 'Сегодня всё плохо.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'enchante', 'enchanté', 'приятно познакомиться', 'Enchanté de vous voir.', 'Приятно вас видеть.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'bienvenue', 'bienvenue', 'добро пожаловать', 'Bienvenue à Paris.', 'Добро пожаловать в Париж.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'bonne-journee', 'bonne journée', 'хорошего дня', 'Bonne journée, Luc.', 'Хорошего дня, Люк.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'bonne-soiree', 'bonne soirée', 'хорошего вечера', 'Bonne soirée, Nora.', 'Хорошего вечера, Нора.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'a-demain', 'à demain', 'до завтра', 'À demain au bureau.', 'До завтра в офисе.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'a-tout-a-l-heure', "à tout à l'heure", 'до скорого', "À tout à l'heure, Max.", 'До скорого, Макс.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'avec-plaisir', 'avec plaisir', 'с удовольствием', 'Avec plaisir, madame.', 'С удовольствием, мадам.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'je-vous-en-prie', 'je vous en prie', 'пожалуйста', 'Je vous en prie.', 'Пожалуйста.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'felicitations', 'félicitations', 'поздравляю', 'Félicitations pour le projet.', 'Поздравляю с проектом.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'bon-courage', 'bon courage', 'удачи', 'Bon courage pour demain.', 'Удачи на завтра.'),
  phrase('A2', 'topic.greetings', 'lesson.a2.greetings-family', 'quel-plaisir', 'quel plaisir !', 'как приятно!', 'Quel plaisir de vous revoir !', 'Как приятно увидеть вас снова!'),

  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'cousine', 'cousine', 'двоюродная сестра', 'la', 'feminine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'oncle', 'oncle', 'дядя', "l'", 'masculine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'tante', 'tante', 'тётя', 'la', 'feminine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'neveu', 'neveu', 'племянник', 'le', 'masculine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'niece', 'nièce', 'племянница', 'la', 'feminine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'parent', 'parent', 'родитель', 'le', 'masculine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'voisin', 'voisin', 'сосед', 'le', 'masculine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'voisine', 'voisine', 'соседка', 'la', 'feminine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'couple', 'couple', 'пара', 'le', 'masculine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'mariage', 'mariage', 'брак', 'le', 'masculine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'anniversaire', 'anniversaire', 'день рождения', "l'", 'masculine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'fiance', 'fiancé', 'жених', 'le', 'masculine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'fiancee', 'fiancée', 'невеста', 'la', 'feminine'),
  noun('A2', 'topic.family', 'lesson.a2.greetings-family', 'relation', 'relation', 'отношение', 'la', 'feminine'),

  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'petit-dejeuner', 'petit déjeuner', 'завтрак', 'le', 'masculine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'dejeuner', 'déjeuner', 'обед', 'le', 'masculine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'diner', 'dîner', 'ужин', 'le', 'masculine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'dessert', 'dessert', 'десерт', 'le', 'masculine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'legume', 'légume', 'овощ', 'le', 'masculine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'fruit', 'fruit', 'фрукт', 'le', 'masculine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'poulet', 'poulet', 'курица', 'le', 'masculine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'gateau', 'gâteau', 'торт', 'le', 'masculine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'beurre', 'beurre', 'масло', 'le', 'masculine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'confiture', 'confiture', 'варенье', 'la', 'feminine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'bouteille', 'bouteille', 'бутылка', 'la', 'feminine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'verre', 'verre', 'стакан', 'le', 'masculine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'faim', 'faim', 'голод', 'la', 'feminine'),
  noun('A2', 'topic.food', 'lesson.a2.food-shopping', 'soif', 'soif', 'жажда', 'la', 'feminine'),

  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'marron', 'marron', 'коричневый'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'rose', 'rose', 'розовый'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'violet', 'violet', 'фиолетовый'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'clair', 'clair', 'светлый'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'sombre', 'sombre', 'тёмный'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'jeune', 'jeune', 'молодой'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'vieux', 'vieux', 'старый'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'facile', 'facile', 'лёгкий'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'difficile', 'difficile', 'трудный'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'propre', 'propre', 'чистый'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'sale', 'sale', 'грязный'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'fort', 'fort', 'сильный'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'faible', 'faible', 'слабый'),
  adjective('A2', 'topic.colors-adjectives', 'lesson.a2.colors-adjectives', 'content', 'content', 'довольный'),

  determiner('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'onze', 'onze', 'одиннадцать'),
  determiner('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'douze', 'douze', 'двенадцать'),
  determiner('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'treize', 'treize', 'тринадцать'),
  determiner('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'quatorze', 'quatorze', 'четырнадцать'),
  determiner('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'quinze', 'quinze', 'пятнадцать'),
  determiner('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'seize', 'seize', 'шестнадцать'),
  noun('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'minute', 'minute', 'минута', 'la', 'feminine'),
  noun('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'semaine', 'semaine', 'неделя', 'la', 'feminine'),
  noun('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'mois', 'mois', 'месяц', 'le', 'masculine'),
  noun('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'annee', 'année', 'год', "l'", 'feminine'),
  noun('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'date', 'date', 'дата', 'la', 'feminine'),
  noun('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'calendrier', 'calendrier', 'календарь', 'le', 'masculine'),
  noun('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'horloge', 'horloge', 'часы', "l'", 'feminine'),
  noun('A2', 'topic.numbers-time', 'lesson.a2.numbers-time', 'temps', 'temps', 'время', 'le', 'masculine'),

  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'cuisine', 'cuisine', 'кухня', 'la', 'feminine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'salon', 'salon', 'гостиная', 'le', 'masculine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'salle-de-bain', 'salle de bain', 'ванная комната', 'la', 'feminine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'armoire', 'armoire', 'шкаф', "l'", 'feminine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'canape', 'canapé', 'диван', 'le', 'masculine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'miroir', 'miroir', 'зеркало', 'le', 'masculine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'serviette', 'serviette', 'полотенце', 'la', 'feminine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'refrigerateur', 'réfrigérateur', 'холодильник', 'le', 'masculine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'balcon', 'balcon', 'балкон', 'le', 'masculine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'etage', 'étage', 'этаж', "l'", 'masculine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'voisinage', 'voisinage', 'соседство', 'le', 'masculine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'sonnette', 'sonnette', 'звонок', 'la', 'feminine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'couloir', 'couloir', 'коридор', 'le', 'masculine'),
  noun('A2', 'topic.everyday-objects-home', 'lesson.a2.objects-home', 'oreiller', 'oreiller', 'подушка', "l'", 'masculine'),

  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'preparer', 'préparer', 'готовить', 'Je prépare le dîner.', 'Я готовлю ужин.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'se-depecher', 'se dépêcher', 'спешить', 'Je me dépêche ce matin.', 'Я спешу сегодня утром.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'se-reposer', 'se reposer', 'отдыхать', 'Je me repose après le travail.', 'Я отдыхаю после работы.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'cuisiner', 'cuisiner', 'готовить еду', 'Je cuisine ce soir.', 'Я готовлю сегодня вечером.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'nettoyer', 'nettoyer', 'убирать', 'Je nettoie la cuisine.', 'Я убираю кухню.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'sortir', 'sortir', 'выходить', 'Je sors à midi.', 'Я выхожу в полдень.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'dejeuner-verbe', 'déjeuner', 'обедать', 'Je déjeune à midi.', 'Я обедаю в полдень.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'diner-verbe', 'dîner', 'ужинать', 'Je dîne avec ma famille.', 'Я ужинаю с семьёй.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'se-promener', 'se promener', 'гулять', 'Je me promène dans le parc.', 'Я гуляю в парке.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'appeler', 'appeler', 'звонить', "J'appelle ma mère.", 'Я звоню маме.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'envoyer', 'envoyer', 'отправлять', "J'envoie un message.", 'Я отправляю сообщение.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'repondre', 'répondre', 'отвечать', 'Je réponds vite.', 'Я отвечаю быстро.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'visiter', 'visiter', 'посещать', 'Je visite la ville.', 'Я посещаю город.'),
  verb('A2', 'topic.daily-routine', 'lesson.a2.daily-routine', 'reserver', 'réserver', 'бронировать', 'Je réserve une table.', 'Я бронирую столик.'),

  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'universite', 'université', 'университет', "l'", 'feminine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'patron', 'patron', 'начальник', 'le', 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'emploi', 'emploi', 'работа', "l'", 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'metier', 'métier', 'профессия', 'le', 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'projet', 'projet', 'проект', 'le', 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'document', 'document', 'документ', 'le', 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'dossier', 'dossier', 'досье', 'le', 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'message', 'message', 'сообщение', 'le', 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'rendez-vous', 'rendez-vous', 'встреча', 'le', 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'formulaire', 'formulaire', 'форма', 'le', 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'entretien', 'entretien', 'собеседование', "l'", 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'reunion', 'réunion', 'собрание', 'la', 'feminine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'salaire', 'salaire', 'зарплата', 'le', 'masculine'),
  noun('A2', 'topic.school-work-basics', 'lesson.a2.school-work', 'contrat', 'contrat', 'контракт', 'le', 'masculine'),

  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'aeroport', 'aéroport', 'аэропорт', "l'", 'masculine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'valise', 'valise', 'чемодан', 'la', 'feminine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'passeport', 'passeport', 'паспорт', 'le', 'masculine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'hotel', 'hôtel', 'отель', "l'", 'masculine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'chambre', 'chambre', 'комната', 'la', 'feminine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'chemin', 'chemin', 'путь', 'le', 'masculine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'retard', 'retard', 'опоздание', 'le', 'masculine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'depart', 'départ', 'отправление', 'le', 'masculine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'arrivee', 'arrivée', 'прибытие', "l'", 'feminine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'voyage', 'voyage', 'путешествие', 'le', 'masculine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'frontiere', 'frontière', 'граница', 'la', 'feminine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'pont', 'pont', 'мост', 'le', 'masculine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'parking', 'parking', 'парковка', 'le', 'masculine'),
  noun('A2', 'topic.transport-travel', 'lesson.a2.transport-travel', 'circulation', 'circulation', 'движение', 'la', 'feminine'),

  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'boutique', 'boutique', 'бутик', 'la', 'feminine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'reduction', 'réduction', 'скидка', 'la', 'feminine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'commande', 'commande', 'заказ', 'la', 'feminine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'rabais', 'rabais', 'уценка', 'le', 'masculine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'panier', 'panier', 'корзина', 'le', 'masculine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'remboursement', 'remboursement', 'возврат денег', 'le', 'masculine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'choix', 'choix', 'выбор', 'le', 'masculine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'facture', 'facture', 'счёт', 'la', 'feminine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'qualite', 'qualité', 'качество', 'la', 'feminine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'marque', 'marque', 'бренд', 'la', 'feminine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'essayage', 'essayage', 'примерка', "l'", 'masculine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'article', 'article', 'товар', "l'", 'masculine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'promotion', 'promotion', 'акция', 'la', 'feminine'),
  noun('A2', 'topic.shopping', 'lesson.a2.food-shopping', 'livraison', 'livraison', 'доставка', 'la', 'feminine'),

  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'epaule', 'épaule', 'плечо', "l'", 'feminine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'doigt', 'doigt', 'палец', 'le', 'masculine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'genou', 'genou', 'колено', 'le', 'masculine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'visage', 'visage', 'лицо', 'le', 'masculine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'oreille', 'oreille', 'ухо', "l'", 'feminine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'dent', 'dent', 'зуб', 'la', 'feminine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'gorge', 'gorge', 'горло', 'la', 'feminine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'medicament', 'médicament', 'лекарство', 'le', 'masculine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'pharmacie', 'pharmacie', 'аптека', 'la', 'feminine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'fatigue', 'fatigue', 'усталость', 'la', 'feminine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'blessure', 'blessure', 'травма', 'la', 'feminine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'toux', 'toux', 'кашель', 'la', 'feminine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'rhume', 'rhume', 'простуда', 'le', 'masculine'),
  noun('A2', 'topic.body-health-basics', 'lesson.a2.body-health', 'pansement', 'pansement', 'пластырь', 'le', 'masculine'),

  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'devoir', 'devoir', 'быть должным', 'Je dois partir.', 'Я должен уйти.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'pouvoir', 'pouvoir', 'мочь', 'Je peux aider.', 'Я могу помочь.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'savoir', 'savoir', 'знать', 'Je sais lire.', 'Я умею читать.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'vouloir', 'vouloir', 'хотеть', 'Je veux du thé.', 'Я хочу чаю.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'continuer', 'continuer', 'продолжать', 'Je continue le travail.', 'Я продолжаю работу.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'decider', 'décider', 'решать', 'Je décide vite.', 'Я быстро решаю.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'expliquer', 'expliquer', 'объяснять', "J'explique la règle.", 'Я объясняю правило.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'oublier', 'oublier', 'забывать', "J'oublie parfois.", 'Я иногда забываю.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'montrer', 'montrer', 'показывать', 'Je montre la carte.', 'Я показываю карту.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'utiliser', 'utiliser', 'использовать', "J'utilise le téléphone.", 'Я использую телефон.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'changer', 'changer', 'менять', 'Je change de plan.', 'Я меняю план.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'rencontrer', 'rencontrer', 'встречать', 'Je rencontre mon collègue.', 'Я встречаю коллегу.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'choisir', 'choisir', 'выбирать', 'Je choisis une table.', 'Я выбираю столик.'),
  verb('A2', 'topic.common-verbs', 'lesson.a2.common-verbs', 'gagner', 'gagner', 'выигрывать', 'Je gagne du temps.', 'Я выигрываю время.'),
] as const;

export const phase11SourceLists = {
  A1: phase11A1SourceList,
  A2: phase11A2SourceList,
} as const;
